#encoding=utf-8
"""
Django settings for Forum project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'iljptg%_t6-q%9*sprlky&yr!!@i!p$7^b=(9-3envx19(0!6('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'verification',
    'registration',
    'registration_email',

)
# 激活有效期
ACCOUNT_ACTIVATION_DAYS = 7
AUTHENTICATION_BACKENDS = (
    'registration_email.auth.EmailBackend',
)
# NOTICE:not work `lambda request, user: '/'
# 登陆后跳转的网站`
LOGIN_REDIRECT_URL = '/verification/index'

# NOTICE:not work only '/accounts/activate/complete/'
REGISTRATION_EMAIL_ACTIVATE_SUCCESS_URL = lambda request, user: '/accounts/activate/complete/'
REGISTRATION_EMAIL_REGISTER_SUCCESS_URL = lambda request, user: '/accounts/register/complete/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '535091412@qq.com'
EMAIL_HOST_PASSWORD = '18758327047lx+'
DEFAULT_FROM_EMAIL = '535091412@qq.com'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Forum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Forum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'C:\Python34\Lib\sqlite3\Forumdb01.db',
        'HOST': '',
	    'PORT': '',
	    'USER': '',
	    'PASSWORD': '',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


# 微博登陆
WEIBO_URL = 'http://codetheme.sinaapp.com'
WEIBO_APP_KEY = ''#详见http://open.weibo.com/authentication/
WEIBO_APP_SERCET = ''#http://open.weibo.com/authentication/
WEIBO_CALLBACK_URL = WEIBO_URL+'/login/weibo_check/'  # 回调地址

# QQ登录
QQ_CLIENT_ID = ""
QQ_CLIENT_SERCET = ""
QQ_REDIRECT_URI = ""
QQ_STATE = ""

# 微信登录
WEIXIN_APP_ID = 'your app id'
WEIXIN_APP_SECRET = 'your app secret'
WEIXIN_REDIRECT_URI = 'http://your_domain.com/redirect_uri'
WEIXIN_SCOPE = 'snsapi_login'# 网页应用目前仅填写snsapi_login即可
WEIXIN_STATE = ''

